wnfs-wg/rs-wnfs

- README.md
- scripts/wnfs.sh
This PR fixes the following **issues**
Moving the repo from previous org to the current one broke the codecov upload. This fixes that and also updates the helper script.
-  Optional, but you can _cd_ into the project root directory and install the script
```bash
sh scripts/wnfs.sh setup
```
- Building the sub projects with the script.
```bash
wnfs build
```
-  Running all tests with the script.
```bash
wnfs test 
```
Fixes #8
> Fix Codecov Upload and Scripts

- crates/wasm/examples/graph/src/blockstore.ts
- crates/wasm/examples/graph/src/types.ts
- crates/wasm/fs/blockstore.rs
- crates/wasm/fs/mod.rs
- crates/wasm/fs/types.rs
- crates/wasm/lib.rs
- crates/wasm/tests/mock.ts
Getting wasm-bindgen to generate more precise type annotations for ts and fixing the putBlock signature
This PR implements the following **features**
- Testing the wasm bindings.
```bash
cd crates/wasm
```
```bash
yarn playwright test
```
Fixes https://github.com/WebNativeFileSystem/rs-wnfs/issues/33
Fixes https://github.com/WebNativeFileSystem/rs-wnfs/issues/32
> Fix wasm-wnfs issues (type annotations, putBlock signature)

- crates/fs/common/metadata.rs
- crates/wasm/fs/metadata.rs
- crates/wasm/fs/mod.rs
- crates/wasm/fs/public/directory.rs
- crates/wasm/tests/fs.spec.ts
- scripts/rs-wnfs.sh
- Provide metadata info in `ls`
- Expose `base_history_on` function
- Expose `load` function
Fixes https://github.com/WebNativeFileSystem/rs-wnfs/issues/34
> Add some WASM APIs

- scripts/rs-wnfs.sh
Currently will just overwrite the `.wasm` that `wasm-pack` generated by running `wasm-bindgen` and `wasm-opt` manually afterwards.
Eventually I believe we can get `--weak-refs` into `wasm-pack`.
> Generate bindings with `--weak-refs` Fixes #40

- crates/fs/public/directory.rs
- crates/fs/public/file.rs
- crates/fs/public/node.rs
- crates/wasm/fs/public/directory.rs
- crates/wasm/fs/public/file.rs
- crates/wasm/fs/public/node.rs
- crates/wasm/lib.rs
- `previousCid`
- `contentCid` for Public Files
- `store` and `load` for Public Files
- `metadata`
- `isFile` and `asFile` for Public Node
> Add more JS APIs

- Cargo.lock
- crates/fs/Cargo.toml
- crates/wasm/Cargo.toml
Bumping the version to 0.1.7 so we can release a new npm package.
(Not a blocker for me though, I've already released 0.1.7-alpha as an alpha package)
> Bump version to 0.1.7

- Cargo.lock
- crates/fs/Cargo.toml
I just went ahead and [published the `skip_ratchet` crate](https://crates.io/crates/skip_ratchet) and updated that as a dependency instead of depending on the github repo URL.
Otherwise I couldn't `cargo publish`:
```sh
$ cargo publish -p wnfs
Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `skip_ratchet` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```
> Use published skip-ratchet crate

- crates/wasm/fs/private/directory.rs
- crates/wasm/tests/private.spec.ts
Fix wasm APIs to reflect RatchetExpSearch implementation
> Fix wasm APIs

- .github/workflows/coverage.yaml
- Cargo.lock
- Cargo.toml
- crates/fs/Cargo.toml
This includes the "expose serializer" PR, so we can stop referring to our fork and instead use the published version.
> Upgrade to libipld 0.14.0

- .github/workflows/checks.yaml
- Cargo.lock
- crates/fs/Cargo.toml
- crates/fs/common/error.rs
- crates/fs/common/metadata.rs
- crates/fs/private/directory.rs
- crates/fs/private/file.rs
- crates/fs/private/forest.rs
- crates/fs/private/hamt/node.rs
- crates/fs/private/node.rs
- crates/fs/public/directory.rs
- crates/fs/public/file.rs
- crates/fs/public/node.rs
- crates/wasm/Cargo.toml
- crates/wasm/fs/metadata.rs
- crates/wasm/fs/private/directory.rs
This PR updates the private and public filesystem implementation to the latest spec
-  Testing the Rust core.
```bash
cargo test -p wnfs --release
```
- Testing the wasm bindings.
```bash
cd crates/wasm
```
```bash
yarn playwright test
```
Fixes https://github.com/wnfs-wg/rs-wnfs/issues/47
Fixes https://github.com/wnfs-wg/rs-wnfs/issues/48
> Update Filesystem Implementation to Match Latest Spec

- Cargo.lock
- crates/fs/Cargo.toml
- crates/fs/common/utils.rs
- crates/fs/private/directory.rs
- crates/fs/private/forest.rs
- crates/fs/private/key.rs
- crates/fs/private/mod.rs
- crates/fs/private/namefilter/bloomfilter.rs
- crates/fs/private/node.rs
- crates/fs/private/rng.rs
- crates/wasm/Cargo.toml
- crates/wasm/fs/private/rng.rs
Leverage `RngCore` in `Rng` implementation
This PR turns `Rng` `random_bytes` method into a default method that depends on `RngCore` implementation. It allows us directly use existing `RngCore` implementations out there without wrapping them, like proptest `TestRng`.
-  Testing the Rust core.
```bash
cargo test -p wnfs --release
```
- Testing the wasm bindings.
```bash
cd crates/wasm
```
```bash
yarn playwright test
```
Fixes https://github.com/wnfs-wg/rs-wnfs/issues/55
> Leverage `rand_core::RngCore` implementations in `Rng`

- README.md
Readme fix for installation (script->scripts)
N/A
> minor readme fix while going through code

- README.md
- scripts/rs-wnfs.sh
This PR tries to resolve [the issue](https://github.com/wnfs-wg/rs-wnfs/issues/63) posted yesterday.
This PR fixes/implements the following **bugs/features**
- [ x ] Bug 1: typo error in `README.md` line 193 `script/`
- [ x ] Bug 2: Running build `rs-wnfs build --all` get **wasm-opt command not found**.
- [ x ] Feature: enhance setup script `rs-wnfs.sh`, try to make use of superuser privileges when creating a symlink.
- remove `/usr/local/bin/rs-wnfs`.
- rerun script by command `sh scripts/rs-wnfs.sh setup` and you should see the result:
Fixes #63
> feat: update README & enhance setup script

- codecov.yaml
- crates/wasm/examples/graph/src/index.ts
- crates/wasm/examples/graph/src/tree.ts
- crates/wasm/examples/graph/webpack.config.js
Fixes the WNFS Graph example.
- Build project
```bash
npx webpack
```
- Run project
```bash
npx http-server -p 8080 dist
```
- Open browser
```bash
open http://localhost:8080
```
> Fix example

- wnfs-wasm/fs/private/forest.rs
- wnfs/common/utils.rs
- wnfs/examples/private.rs
- wnfs/private/directory.rs
- wnfs/private/forest.rs
- wnfs/private/hamt/hamt.rs
- wnfs/private/key.rs
- wnfs/private/namefilter/bloomfilter.rs
- wnfs/private/node.rs
- wnfs/private/previous.rs
- wnfs/public/directory.rs
This PR only changes the data format, but minimally changes the actual data stored. Specifically: We never actually generate multivalues in rs-wnfs. So why add support for them?
The reason is being future-proof: We *know* we'll make use of multivalues in the future, so we add support for them *today*, so that *today*'s version of rs-wnfs will have *some* support for them even when future versions of rs-wnfs actually write multivalues.
In this PR:
- the `PrivateForest` type alias changed to use `BTreeSet<Cid>` as value, instead of just `Cid`
- `PrivateForest.set` was renamed to `put`, and it adds to the multivalues at a given key, instead of replacing. There's a performance optimization opportunity here to avoid walking the HAMT twice by creating a `modify`/`upsert` implementation in …
> Make private forest multivalue

- wnfs-bench/hamt.rs
- wnfs/src/common/metadata.rs
- wnfs/src/private/forest.rs
- wnfs/src/private/hamt/node.rs
Putting this up here for discussion.
We can make use of mutability in `Node::set_value` and `Node::remove_value`, by turning values of type `Rc<Node<...>>` into `mut Node<...>` using `Rc::try_unwrap(...).unwrap_or_else(|rc| (*rc).clone())`.
Essentially that'll just give us an owned `Node` if we hold the only reference to it, or it'll clone the inner `Rc`.
Theory is that if the calling code is basically doing lots of changes on the HAMT in a tight loop, that's going to get sped up, since that'll end up being lots of in-place mutation.
The benchmarks don't look *too* promising though. I got ~10% improvements.
To test this, just compare the two commits in the PR against each other. Specifically their `cargo bench -p wnfs-bench node`.
Also, I had to hand-expand the `async_recursion` macro for …
> Use `Rc::try_unwrap` for (possibly?) better performance

- wnfs-wasm/Cargo.toml
- wnfs-wasm/src/fs/private/directory.rs
- wnfs-wasm/src/fs/private/forest.rs
- wnfs-wasm/src/fs/private/node.rs
- wnfs-wasm/src/fs/utils.rs
- wnfs/Cargo.toml
- wnfs/examples/private.rs
- wnfs/src/common/utils.rs
- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
- wnfs/src/private/forest.rs
- wnfs/src/private/hamt/node.rs
- wnfs/src/private/mod.rs
- wnfs/src/private/node.rs
- wnfs/src/private/previous.rs
- wnfs/src/private/privateref.rs
In some cases, we want to be able to deterministically create a directory with seeds generated at userland, for example, from private keys. There is a hacky solution to this by passing a carefully designed rng, but that is likely to break in future versions.
This PR adds the API for accepting user-specified ratchet seed and inumber that solves the problem outlined above. 
This PR implements the following **features**
-  Testing
```bash
rs-wnfs test --all
```
Fixes #86
> Allow user-provided ratchet seed and inumber

- wnfs/proptest-regressions/private/file.txt
- wnfs/src/common/blockstore.rs
- wnfs/src/common/error.rs
- wnfs/src/private/file.rs
- wnfs/src/private/key.rs
I messed up a bit in the spec and forgot about AES-GCM's authentication tag, which is another 16 bytes of overhead added during encryption.
The spec PR: https://github.com/wnfs-wg/spec/pull/57
So, to sum it up: AES-GCM with a 12 bytes IV and a 256-bit key adds a 16 bytes authentication tag.
(That tag's purpose is to check that no process tampered with the ciphertext.)
---
I added a condition to the `MemoryBlockStore` to make sure none of our tests actually exceed the block limit in the future.
Accordingly, I added an error `MaximumBlockSizeExceeded`.
Lastly I fixed the calculation for the maximum length of plaintext for a private file block.
> Fix calculations avoiding to exceed the 2^18 bytes block limit

- wnfs/Cargo.toml
- wnfs/examples/private.rs
- wnfs/examples/privateref.rs
- wnfs/src/lib.rs
- wnfs/src/private/directory.rs
- wnfs/src/private/namefilter/bloomfilter.rs
- wnfs/src/private/node.rs
- wnfs/src/private/privateref.rs
This PR implements the following **bugs/features**
Right now because of how PrivateDirectory constructor works, they don't store the dir right after creating. So the initial revision can be lost in that sense. Unlike `mkdir`, `write`methods which store the things you create in the forest during the operation. We are working on fixing that. This PR adds a fix is that puts the directory in the forest right after creating it.
In addition to that, we don't have a way to search_latest on the root directory. This PR adds support for self lookup by supplying an empty path segment to the lookup function.
-  Testing
```bash
rs-wnfs test --all
```
> feat(api): self lookup & store at construction

- wnfs-wasm/src/fs/metadata.rs
- wnfs-wasm/tests/public.spec.ts
We used to convert the integers in metadata, which are `i128` internally, into `i64` and then pass that off to `wasm-bindgen`, which turned them into `BigInt`s on the javascript side.
`BigInt`s have poor support in many bundlers and still cause issues occasionally. For some reason it caused the integers to come out as `undefined` on the other end. This PR adds two regression tests that verified this.
This PR instead turns the internal `i128`s into `f64`s before passing them to `wasm-bindgen`, which means they come out as normal JS numbers on the other side.
```
$ cd wnfs-wasm
$ yarn playwright test
```
> Fix metadata being passed out to JS as a float instead of a `BigInt`

- wnfs-wasm/src/fs/private/directory.rs
- wnfs-wasm/src/fs/private/file.rs
- wnfs-wasm/tests/private.spec.ts
- wnfs/src/private/file.rs
Adds `get_metadata` function to `PrivateFile` in `wnfs` crate and `metadata` function for the private file and directories. Also adds the `as_node` function to the private directories in WASM.
> feat(api): adds missing metadata functions for the private side

- wnfs/src/lib.rs
- wnfs/src/private/node.rs
Re-factors double_Random and adds `#![deny(unsafe_code)]`
The old one used [transmute](https://doc.rust-lang.org/stable/std/mem/fn.transmute.html)
I benched with two Rng's just in case and it's ~same and added a test
I even implemented the stdlib safer version (with little unsafe) for comparison in case it is still needed for some reason
https://github.com/pinkforest/double-random
> refactor: Double random

- .cargo/config.toml
- .github/workflows/coverage.yaml
- Cargo.toml
Supercedes https://github.com/wnfs-wg/rs-wnfs/pull/158#pullrequestreview-1306266384
Testing in CI
> chore: Strip flags 2

- clippy.toml
- wnfs/src/private/node.rs
- wnfs/src/private/previous.rs
We previously used a feature (The `ignore-interior-mutability` clippy configuration) that was introduced in clippy 1.67: https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#enhancements
This PR stops using that configuration and instead just ignores the warning at every use site.
> chore: Allow clippy versions <1.67

- wnfs-wasm/src/fs/private/forest.rs
- wnfs-wasm/src/fs/private/node.rs
- wnfs-wasm/tests/private.spec.ts
- wnfs/src/private/forest.rs
This PR exposes the hamt merge and diff bindings
-  Testing
```bash
scripts/rs-wnfs.sh test --wasm
```
Fixes #169
> feat(api): add privateforest merge and diff bindings

- wnfs/Cargo.toml
This was already in `dev-dependencies` as it's only used for testing
> chore: Redundant rsa

- wnfs-common/Cargo.toml
- wnfs-hamt/Cargo.toml
- wnfs-namefilter/Cargo.toml
- wnfs/Cargo.toml
sha2 is only used in a test so can be in dev-dependencies, sha3 also can be concentrated in the manifests
> feat: Redundant sha2

- wnfs-common/Cargo.toml
- wnfs-hamt/Cargo.toml
- wnfs-namefilter/Cargo.toml
- wnfs/Cargo.toml
futures-util already comes via futures and it's not used directly so can be cleaned up
> chore: Redundant futures-util manifest

- wnfs-wasm/src/fs/private/share.rs
- wnfs-wasm/tests/server/index.d.ts
- wnfs-wasm/tests/server/index.ts
- wnfs/src/private/share.rs
Fixes #196 
The idea is to provide a function that finds the maximum share count for available shares. This allows callers to check all share counts they might have missed in between.
I added another test that checks after a bunch of shares that the maximum share counter is returned.
> fix: `find_latest_share_counter` finds the last share count

- release-please-config.json
- wnfs-hamt/Cargo.toml
- wnfs-namefilter/Cargo.toml
- wnfs/Cargo.toml
Hoping this & some additional tagging may fix stuff.
It certainly doesn't break anything, so worth a try?
> chore: Use version & path dependencies inter-workspace at the same time

- wnfs-common/src/metadata.rs
Adds metadata mutation API. Closes #209 
This PR fixes/implements the following **bugs/features**
Motivation: necessary in order to add a pre-encryption file checksum field to metadata for file deduplication across multiple uploads in the same PrivateForest
I added doctests for each of these and they pass.
Closes #209
> feat: adding mutation api for metadata. cleaning up clippy complaints

- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
Explain the **motivation** for making this change. What existing problem does the pull request solve?
See #210- prep for integrating with Filecoin
This doesn't pass doctests- I'm pretty sure without adding some interior mutability, we can't make the desired workflow in #210 work. open to being told I'm wrong. The doctest error is illustrative, and I gave more details in #210.
Closes #210 
(none of the above)
> feat: `open_file_mut` function for getting `&mut PrivateFile` references

- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
This PR contains changes I needed to made while hacking on [wnfs-fuse](https://github.com/Frando/wnfs-fuse) at IPFSThing.
- Public getter method on `PrivateDirectory` to get the entries. `ls` exists, but loads all the metadata, which is expensive if not needed
- Make `PrivateFile::get_content_size_upper_bound` public (to have something to report as filesize - even if inaccurate). It might be a good idea to add the actual filesize to the metadata instead.
- Add a new method `PrivateFile::read_at` to read `size` bytes from `offset`. This makes use of `stream_content` internally and does the block and offset calculations
> feat: Add `PrivateDirectory::entires`, `PrivateFile::read_at` and make `PrivateFile::get_content_size_upper_bound` public

- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
As it is, the file content streaming implementation can panic if there is a missing chunk.
We should avoid unwrap as much as possible in the code and allow user to handle errors. This PR fixes that with the `try_stream_ext`
```bash 
scripts/rs-wnfs.sh test
```
#228
> fix: propagate missing chunk error

- wnfs-wasm/src/fs/private/directory.rs
- wnfs-wasm/tests/private.spec.ts
- wnfs-wasm/tests/public.spec.ts
- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
- wnfs/src/public/directory.rs
rs-wnfs `get_node` fns in `PublicDirectory` and `PrivateDirectory` currently do not replicate the same behavior in webnative when a non-existent path segment is specified. It returns an`Err(...)` instead of a `Ok(None)` which translates to `null` on the js side.
This PR solves that although there is the little inconvenience that wasm-bindgen translates `Ok(None)` to `undefined` on the js side.
```bash 
scripts/rs-wnfs.sh test
```
#222
> fix!: get_node should return null on missing path

- wnfs/src/private/previous.rs
- Removed references to `Ratchet`s in public functions
- Replaced these references with `PrivateDirectory`s / `PrivateNode`s
- Ensured all test cases for `previous.rs` compile with these new function signatures and pass test cases
> PrivateNodeHistory::of & PrivateHistory::of

- README.md
- wnfs-wasm/README.md
- wnfs/README.md
Update the readme examples and elaborate on some of the filesystem concepts.
> chore: update READMEs

- wnfs-wasm/src/fs/private/access_key.rs
- wnfs-wasm/tests/mock.ts
- wnfs-wasm/tests/private.spec.ts
- wnfs/src/private/directory.rs
- wnfs/src/private/keys/access.rs
- wnfs/src/private/previous.rs
- wnfs/src/public/directory.rs
Fixes #294 
This PR fixes/implements the following **bugs/features**
Adds ability to serialize access-key so it can be preserved across sessions
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Added a test to verify changes work
Fixes #294
> feat: expose AccessKey encode/decode api

- .github/workflows/checks.yaml
- .github/workflows/release.yml
- README.md
- scripts/rs-wnfs.sh
- wnfs-wasm/.gitignore
- wnfs-wasm/README.md
- wnfs-wasm/package.json
- wnfs-wasm/src/loaders/workerd.js
- wnfs-wasm/tests/mock.ts
- wnfs-wasm/tests/server/index.d.ts
- wnfs-wasm/tests/server/index.ts
- wnfs-wasm/tests/server/webpack.config.cjs
- wnfs-wasm/yarn.lock
This PR implements the following features:
This PR updates JS packaging and binding to make the package easier to load in bundlers, node, and Cloudflare Workers. 
It's not perfect! We are testing out improvements over to support SvelteKit and other environments over in https://github.com/fission-codes/wasm-js. But it should be a good starting point, and it will help us with testing in the ODD SDK.
Note that the `web` target is a special case for Cloudflare workers. Excepting node, most other environments will use the `bundler` target.
Run the Webpack test suite. The tests should still work and pass. 👌 
None yet. Happy to open one.
> chore: Update JS binding and packaging

- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
- wnfs/src/private/node/header.rs
- wnfs/src/private/node/node.rs
- wnfs/src/private/previous.rs
This simply caches the result of `get_revision_name()`, as that's accessed quite a lot and would otherwise cause lots of repeated BigUint operations, which are costly.
It improves performance of general filesystem operations by roughly 20% in my limited testing (I compared runtime of `cargo test --lib -p wnfs -- "private::directory::"`).
> fix: Improve performance of `get_revision_name()`

- wnfs-wasm/src/fs/public/directory.rs
- wnfs-wasm/tests/public.spec.ts
- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
- wnfs/src/private/node/node.rs
- wnfs/src/public/directory.rs
Fixes #316 (although what was missing was actually `cp` for *Public* directory, not private)
Since #306 we can actually do a more efficient copy of external `PrivateFile` content that doesn't require re-encryption, because we can directly refer to the old content (using the `bare_name` property of `ExternalFileContent`).
I've decided to set this as the default copy algorithm. There's no benefit to re-encrypting the actual content bytes. You already get the key rotation on the wrapping `PrivateFile`, and it doesn't implicitly give you access to anything else besides the bytes you're supposed to be able to read.
I think this supersedes #256 at least in terms of what Banyan needs.
> feat: Implement public directory cp & more efficient copy for `PrivateFile`

- .release-please-manifest.json
- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
Also ignoring the `needless_pass_by_ref_mut` lint.
That lint has a bug that causes false positives. It'll be fixed when this is released: https://github.com/rust-lang/rust-clippy/pull/11314
However, it's a nightly lint, so unfortunately I can't ignore it via a `#[allow(clippy::needless_pass_by_ref_mut)]`, since that makes *stable* clippy fail with an unknown lint error.
So I made it ignore all lints from the `suspicious` group on the affected functions.
> chore: Release 0.1.24

- wnfs-nameaccumulator/src/name.rs
- wnfs/Cargo.toml
- wnfs/examples/write_proofs.rs
- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
- wnfs/src/private/forest/hamt.rs
- wnfs/src/private/forest/proofs.rs
- wnfs/src/private/forest/traits.rs
- wnfs/src/private/link.rs
- wnfs/src/private/node/header.rs
- wnfs/src/private/node/node.rs
- wnfs/src/private/previous.rs
- wnfs/src/private/share.rs
`BigUint::modexp` operations take up to 14ms in Wasm on my machine, and it's the core operation for `NameAccumulator`s.
This introduces a LRU cache inside `HamtForest` that caches `NameAccumulator` operations.
This is much more reliable than sprinkling `OnceCell`s every here and there, since
1. The "eviction" of these `OnceCell` caches depends on the lifetime of the object they're contained in, and it's harder to make these structs longer-lived in some cases.
2. Sometimes the structs that these `OnceCell`s are contained inside are mutable via `&mut self` operations. We need to remember to always empty these `OnceCell`s when that happens. This is bad for two reasons: (1) we might forget doing so sometimes, keeping stale, incorrectly cached data around and (2) even though the cache doesn't …
> fix: More reliably cache `NameAccumulator` modexps

- wnfs-wasm/package.json
The release action was trying to re-publish 0.1.23, this PR bumps it up to 0.1.24
> fix: bump package.json version number to 0.1.24

- wnfs-nameaccumulator/src/name.rs
- wnfs/src/lib.rs
- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
- wnfs/src/private/keys/snapshots/wnfs__private__keys__access__snapshot_tests__access_key-2.snap
- wnfs/src/private/node/keys.rs
- wnfs/src/private/snapshots/wnfs__private__directory__snapshot_tests__private_fs.snap
- wnfs/src/public/directory.rs
- wnfs/src/public/file.rs
- wnfs/src/public/node/snapshots/wnfs__public__node__node__snapshot_tests__public_file_and_directory_nodes-2.snap
- wnfs/src/public/node/snapshots/wnfs__public__node__node__snapshot_tests__public_file_and_directory_nodes.snap
- wnfs/src/public/node/snapshots/wnfs__public__node__node__snapshot_tests__public_fs.snap
- wnfs/src/public/snapshots/wnfs__public__directory__snapshot_tests__directory_with_children.snap
- wnfs/src/public/snapshots/wnfs__public__directory__snapshot_tests__directory_with_previous_links.snap
- wnfs/src/public/snapshots/wnfs__public__directory__snapshot_tests__empty_directory.snap
- wnfs/src/public/snapshots/wnfs__public__file__snapshot_tests__file_with_previous_links.snap
- wnfs/src/public/snapshots/wnfs__public__file__snapshot_tests__simple_file.snap
- wnfs/src/root_tree.rs
- wnfs/src/snapshots/wnfs__root_tree__snapshot_tests__root_filesystems.snap
- Sets WNFS data format version to 1.0.0 (and updates the version checks. They match against 1.0.x now)
- Updates the domain separation strings (we added versioning to them & changed them from saying `deriv` to saying `derivation`)
- Updates snapshots, since the version number changed & the domain separation strings means the keys changed, too.
> Update data format version to 1.0.0 and adjust domain separation strings according to the latest spec

- wnfs-wasm/package.json
This PR makes the following changes:
This PR brings in improvements from the `wasm-js` project in this PR: https://github.com/fission-codes/wasm-js/pull/7
Adding the `browser` entry point and placing it before the `node` makes sure we resolve the bundler target for SSR in SvelteKit and NextJS.
NextJS unfortunately resolves `main` before anything and is unable to handle CommonJS. As a result, we are dropping `main` which was only intended for projects using older versions of `node`.
Testing this fully would require a SvelteKit and NextJS example app. We have these examples over in the `wasm-js` repo: https://github.com/fission-codes/wasm-js/tree/main/examples
None yet. Let me know if you'd like one.
> chore: Update JS package exports

- wnfs-nameaccumulator/src/name.rs
- wnfs/src/private/directory.rs
- wnfs/src/private/node/node.rs
This fixes two bugs reported by @icidasset:
- We don't respect the `search_latest` parameter during calls like `write` or `mkdir` for the root directory.
- The mountpoint was incorrectly set in `search_latest_node` to the empty name accumulator in some cases.
> fix: Fix `search_latest` on `write` and file mountpoints

- wnfs-common/Cargo.toml
- wnfs-common/src/link.rs
- wnfs-hamt/Cargo.toml
- wnfs-hamt/src/node.rs
- wnfs/Cargo.toml
- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
- wnfs/src/private/link.rs
- wnfs/src/public/directory.rs
- wnfs/src/public/file.rs
Subsumes #245 
They had an API change where `OnceCell::new_with` would now only build *filled* `OnceCell`s, not empty ones anymore, so its parameter type changed from `Option<T>` to just `T`.
Means I had simply had to either call `OnceCell::new_with` when it's `Some` or otherwise use `OnceCell::new()` (via `Default`).
> chore: Update `async-once-cell` to v0.5

- wnfs-common/src/metadata.rs
- wnfs/examples/README.md
- wnfs/examples/file_variants.rs
- wnfs/examples/private.rs
- wnfs/examples/write_proofs.rs
- wnfs/src/private/file.rs
- wnfs/src/public/directory.rs
- wnfs/src/public/file.rs
- wnfs/src/public/node/node.rs
- wnfs/src/utils/test.rs
This work enables File Variants (https://github.com/wnfs-wg/roadmap/issues/7).
Essentially it exposes the struct used for storing pointers & keys to content encrypted inside the `PrivateForest` as well as some utilities to store these in a file's (or directory's) `Metadata`.
See also the new example `file_variants.rs`.
> feat: Implement storing externally encrypted content in `Metadata`

- README.md
- wnfs-common/src/blockstore.rs
- wnfs-common/src/metadata.rs
- wnfs-wasm/src/fs/private/share.rs
- wnfs-wasm/tests/share.spec.ts
- wnfs/README.md
- wnfs/examples/file_variants.rs
- wnfs/examples/mnemonic_based.rs
- wnfs/examples/private.rs
- wnfs/examples/public.rs
- wnfs/examples/tiered_blockstores.rs
- wnfs/examples/write_proofs.rs
- wnfs/src/error.rs
- wnfs/src/lib.rs
- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
- wnfs/src/private/forest/hamt.rs
- wnfs/src/private/forest/traits.rs
- wnfs/src/private/mod.rs
- wnfs/src/private/node/header.rs
- wnfs/src/private/node/node.rs
- wnfs/src/private/previous.rs
- wnfs/src/private/share.rs
- wnfs/src/public/directory.rs
- wnfs/src/public/file.rs
- wnfs/src/public/mod.rs
- wnfs/src/public/node/node.rs
- wnfs/src/root_tree.rs
This PR adds and updates existing documentation, doc tests and makes other API clean ups.
-  Testing the code.
```bash
scripts/wnfs.sh test
```
> feat: Remove `Share` struct, add documentation, add `rc` constructor variants

- wnfs-common/src/async_serialize.rs
- wnfs-common/src/utils/send_sync_poly.rs
- wnfs-unixfs-file/src/balanced_tree.rs
- wnfs-unixfs-file/src/builder.rs
- wnfs-unixfs-file/src/chunker.rs
- wnfs-unixfs-file/src/chunker/fixed.rs
- wnfs-unixfs-file/src/chunker/rabin.rs
- wnfs-unixfs-file/src/types.rs
- wnfs-unixfs-file/src/unixfs.rs
- wnfs-wasm/src/fs/public/directory.rs
- wnfs-wasm/src/fs/public/file.rs
- wnfs-wasm/tests/mock.ts
- wnfs-wasm/tests/public.spec.ts
- wnfs/Cargo.toml
- wnfs/examples/mnemonic_based.rs
- wnfs/examples/public.rs
- wnfs/src/private/directory.rs
- wnfs/src/private/file.rs
- wnfs/src/private/share.rs
- wnfs/src/public/directory.rs
- wnfs/src/public/file.rs
- wnfs/src/public/node/node.rs
- wnfs/src/public/node/snapshots/wnfs__public__node__node__snapshot_tests__public_file_and_directory_nodes-2.snap
- wnfs/src/public/node/snapshots/wnfs__public__node__node__snapshot_tests__public_fs.snap
- wnfs/src/public/snapshots/wnfs__public__directory__snapshot_tests__directory_with_children.snap
- wnfs/src/public/snapshots/wnfs__public__directory__snapshot_tests__directory_with_previous_links.snap
- wnfs/src/public/snapshots/wnfs__public__file__snapshot_tests__file_with_previous_links.snap
- wnfs/src/public/snapshots/wnfs__public__file__snapshot_tests__simple_file.snap
- wnfs/src/root_tree.rs
Previously we only had a CID-based API that just "set" the file CID to some value.
This now requires public files to encode their content as byte arrays.
Now the public and private APIs are very similar, both operate on the byte-array level for files.
Made possible through #375 
TODO:
> feat: Bytes-based public file writing API

- wnfs-wasm/src/fs/public/file.rs
- wnfs-wasm/tests/public.spec.ts
- wnfs/src/public/file.rs
Adds back the public content CID functionality that was previously removed, under the new name `get_raw_content_cid`. This method is async as opposed to its predecessor.
I've added a new test to [wnfs-wasm/tests/public.spec.ts](https://github.com/wnfs-wg/rs-wnfs/compare/get_raw_content_cid?expand=1#diff-636f0cb11fda133fb5499edf39f348da78cde25e0359199ac7df4600f94dced9)
> feat: add `get_raw_content_cid`

- wnfs-wasm/src/fs/private/file.rs
- wnfs-wasm/src/fs/public/file.rs
- wnfs-wasm/tests/private.spec.ts
- wnfs-wasm/tests/public.spec.ts
- wnfs/src/private/file.rs
- wnfs/src/public/file.rs
I've made it so that the public and private APIs for reading content better match.
`wnfs` changes:
- Made the length param optional and renamed the offset param to match the public side.
- Copied the doc test from the public side to the private side.
- Made it so that `PrivateFile.get_content` uses its `read_at` method.
- Added `PublicFile.get_content` to reflect the private side.
`wnfs-wasm` changes:
- Added `PrivateFile.read_at`
- Made it so that `PrivateFile.get_content` uses its `read_at` method.
- Added `PublicFile.get_content`
- Adjusted tests to use new and changed methods.
Added and adjusted some tests.
> Match the public and private APIs for content reading

- wnfs/src/public/directory.rs
*Of course* I think of this *right after* publishing the next version.
Getting this in there quickly before I forget it for the next time.
> chore: Remove leftover logging value

- wnfs-common/src/metadata.rs
- wnfs-hamt/src/diff.rs
- wnfs-hamt/src/merge.rs
- wnfs-hamt/src/node.rs
- wnfs-hamt/src/pointer.rs
- wnfs-nameaccumulator/src/name.rs
- wnfs-unixfs-file/src/balanced_tree.rs
- wnfs-unixfs-file/src/builder.rs
- wnfs-unixfs-file/src/protobufs.rs
- wnfs/proptest-regressions/public/directory.txt
- wnfs/proptest-regressions/public/node/node.txt
- wnfs/src/private/file.rs
- wnfs/src/public/directory.rs
- wnfs/src/public/file.rs
- wnfs/src/public/node/node.rs
This implements three functions:
- `PublicDirectory::reconcile` which takes two directories & reconciles all changes between them. Think of this as similar to `get pull`, but where conflicts in files are merged automatically via a simple tie-breaking mechanism on the file hash. The return value indicates whether and which files were affected by the automatic merge, if at all.
- `PublicDirectory::merge`, the underlying function for `reconcile`, but which doesn't take into account if one of the directories may have been "ahead" in history. Use only if you know what you're doing, otherwise opt for `reconcile`.
- `PublicNode::causal_compare`, the underlying function in `reconcile` that figures out whether one version of a node is "ahead" of another or behind, or if they're two conflicting …
> feat: implement `PublicDirectory` conflict reconciliation

- wnfs-common/src/link.rs
- wnfs/src/private/directory.rs
- wnfs/src/public/directory.rs
- wnfs/src/public/file.rs
This is an edge case I came across while implementing private conflict reconciliation.
Essentially we have this setup:
- Both replicas share the same state of a single file, e.g. at "public/a/b.txt".
- Then one replica deletes that file
- The other replica does an unrelated write, e.g. it adds "public/file.txt"
- Both replicas merge again
What happened previously was:
- We detected that two independent writes were done on the root directory
- We run a deep merge on both directories. The `b.txt` file gets re-introduced (the remove gets "overwritten"), because we don't re-check the causal relationship of the "a" directories.
We now check the causal relationship between directories on every level (recursively).
I also removed the `merge` function, as otherwise it'd be hard to disentangle the …
> fix: Public reconciliation of a concurrent write and remove (of independent paths)
